"""
Recommendation ranking + deduplication for S3 intelligence analysis.

After:
    - signal extraction
    - agent reasoning
    - safety validation
    - historical filtering

the system still needs to:
    1. deduplicate recommendations
    2. prioritize the most operationally important findings
    3. avoid noisy optimization spam
    4. prioritize durability/security over aggressive savings

Ranking philosophy:
    reliability + security > cost optimization

A dangerous public bucket should ALWAYS rank above:
    - Glacier savings
    - lifecycle opportunities
    - tiering suggestions

Similarly:
    replication failures should outrank storage cleanup.

Priority balances:
    severity
    confidence
    operational risk
    durability impact
    estimated savings relevance
"""

from __future__ import annotations

from typing import List

from agent.s3_agent.types import (
    Recommendation,
    Severity,
)


# ---------------------------------------------------------------------------
# Severity scoring
# ---------------------------------------------------------------------------

_SEV_SCORE = {
    Severity.CRITICAL: 6,
    Severity.HIGH: 5,
    Severity.WARNING: 4,
    Severity.MEDIUM: 3,
    Severity.LOW: 2,
    Severity.INFO: 1,
}


# ---------------------------------------------------------------------------
# Operational risk divisor
# Higher risk = lower automatic ranking score
# ---------------------------------------------------------------------------

_RISK_DIVISOR = {
    "low": 1.0,
    "medium": 1.5,
    "high": 2.2,
}


# ---------------------------------------------------------------------------
# Durability-sensitive rule boosts
# Reliability > Cost
# ---------------------------------------------------------------------------

DURABILITY_PRIORITY_BOOST = {
    "s3.reliability.replication_failures": 2.5,
    "s3.reliability.versioning_disabled": 1.8,
    "s3.security.public_access": 2.5,
    "s3.security.encryption_disabled": 1.8,
}


# ---------------------------------------------------------------------------
# Optimization deprioritization
# Avoid cost-noise dominating dashboard
# ---------------------------------------------------------------------------

OPTIMIZATION_PENALTY_RULES = {
    "s3.cost.intelligent_tiering": 0.85,
    "s3.cost.glacier_candidate": 0.80,
}


# ---------------------------------------------------------------------------
# Priority calculation
# ---------------------------------------------------------------------------

def _priority(rec: Recommendation) -> float:
    """
    Higher score = surfaced earlier.
    """

    severity_score = _SEV_SCORE.get(
        rec.severity,
        2,
    )

    risk_divisor = _RISK_DIVISOR.get(
        rec.operational_risk,
        1.5,
    )

    base_score = (
        severity_score * rec.confidence
    ) / risk_divisor

    #
    # Durability / security boost
    #
    base_score *= DURABILITY_PRIORITY_BOOST.get(
        rec.rule_id,
        1.0,
    )

    #
    # Optimization penalty
    #
    base_score *= OPTIMIZATION_PENALTY_RULES.get(
        rec.rule_id,
        1.0,
    )

    #
    # Retrieval-risk penalty
    #
    retrieval_impact = (
        rec.retrieval_impact or ""
    ).lower()

    if (
        "hours" in retrieval_impact
        or "latency" in retrieval_impact
    ):
        base_score *= 0.90

    #
    # Manual-only penalty
    #
    if rec.manual_only:
        base_score *= 0.95

    return round(base_score, 4)


# ---------------------------------------------------------------------------
# Deduplication
# ---------------------------------------------------------------------------

def deduplicate(
    recs: List[Recommendation],
) -> List[Recommendation]:

    """
    Deduplicate recommendations generated by multiple agents.

    Keep the highest-priority recommendation
    for each rule_id.
    """

    by_rule = {}

    for rec in recs:

        existing = by_rule.get(rec.rule_id)

        if (
            existing is None
            or _priority(rec) > _priority(existing)
        ):
            by_rule[rec.rule_id] = rec

    return list(by_rule.values())


# ---------------------------------------------------------------------------
# Ranking
# ---------------------------------------------------------------------------

def rank(
    recs: List[Recommendation],
) -> List[Recommendation]:

    """
    Deduplicate then sort recommendations
    by operational priority.
    """

    deduped = deduplicate(recs)

    return sorted(
        deduped,
        key=_priority,
        reverse=True,
    )