import logging
from typing import List, Dict, Any, Optional

from connections.db import get_resource_from_db
from aws.ec2 import list_ec2_instances
from aws.s3 import list_s3_buckets
from aws.dynamodb import list_dynamodb_tables
from connections.gcp import list_cloud_storage

logger = logging.getLogger(__name__)

running_resources = 0
idle_resources = 0


async def get_all_resources(force: bool = False):
    """
    Fetch live AWS resources, generate per-resource recommendations,
    then run the LangGraph multi-agent pipeline for critique, verification,
    cross-resource correlation, and quality evaluation.
    """
    logger.info("Fetching all resources from AWS... (force=%s)", force)
    ec2_resources = await list_ec2_instances(force=force)
    s3_resources = await list_s3_buckets(force=force)
    dynamo_resources = await list_dynamodb_tables(force=force)
    resources = ec2_resources + s3_resources + dynamo_resources

    for res in resources:
        if res.get("status") == "running":
            global running_resources
            running_resources += 1
        else:
            global idle_resources
            idle_resources += 1

        if not res.get("last_activity"):
            res["last_activity"] = (
                res.get("last_agent_run")
                or res.get("metadata", {}).get("creation_date")
                or res.get("creation_date")
            )

    resources = _run_langgraph_pipeline(resources)
    return resources


def _run_langgraph_pipeline(resources: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Run the LangGraph multi-agent pipeline on all resources.

    The per-resource recommendations are already generated by the AWS modules.
    This pipeline adds:
      - Critique: quality review of all recommendations
      - Refine: apply critique feedback (up to 2 iterations)
      - Correlate: cross-resource pattern detection
      - Verify: verification gates (confidence, cost, safety)
      - Evaluate: quality metrics tracking
    """
    from agent.core.orchestrator import MultiAgentOrchestrator

    resources_with_recs = [r for r in resources if r.get("recommendations")]
    if not resources_with_recs:
        return resources

    try:
        orchestrator = MultiAgentOrchestrator()
        result = orchestrator.run(resources_with_recs)

        verified_recs = result.get("recommendations", [])
        correlations = result.get("correlations", [])

        rec_by_resource: Dict[str, List[Dict[str, Any]]] = {}
        for rec in verified_recs:
            rid = rec.get("resource_id", "")
            rec_by_resource.setdefault(rid, []).append(rec)

        for res in resources:
            rid = res.get("resource_id", "")
            if rid in rec_by_resource:
                res["recommendations"] = rec_by_resource[rid]

            if correlations:
                involved = [
                    c for c in correlations
                    if rid in c.get("resources_involved", [])
                    or not c.get("resources_involved")
                ]
                if involved:
                    res["correlations"] = involved

        logger.info(
            "LangGraph pipeline complete — %d verified recs, %d correlations",
            len(verified_recs), len(correlations),
        )

    except Exception as e:
        logger.warning("LangGraph pipeline failed, returning raw recommendations: %s", e)

    return resources


def get_resource_by_id(resource_id: str, resource_type: str):
    return get_resource_from_db(resource_id)


def get_running_resource() -> int:
    return running_resources


def get_idle_resource() -> int:
    return idle_resources
